version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: beat-it-up-backend
    ports:
      - "8000:8000"
    # Uncomment for live reload in development:
    volumes:
      - ./backend/app:/app/app

  frontend:
    build:
      context: ./frontend
    container_name: beat-it-up-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    # Uncomment for live reload in development:
    volumes:
      - ./frontend:/app 